name: Deploy to GitHub Pages

on:
  # Trigger the workflow with every push/merge to the `main/master` branch.
  push:
    branches: [master]
  # Allow to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload Ahmed Alshair's website
        uses: withastro/action@v5
        # with:
        # path: . # The root location of Astro project inside the repository. (optional)
        # node-version: 24 # The specific version of Node that should be used to build the website. Defaults to 22. (optional)
        # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build the website. Automatically detected based on lockfile. (optional)
        # build-cmd: npm run build # The command to run to build the website. Runs the package build script/task by default. (optional)
        env:
          HUSKY: 0 # Disables Husky

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
